# Generated by Django 4.2.6 on 2024-02-20 10:46

import apps.account.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.account.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, help_text="활성화 된 유저인지 확인"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, help_text="관리자인지 확인"),
        ),
    ]
